version: "3"
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8-rc
        hostname: rabbitmq
        networks: 
            - net
        ports: 
            - "5672:5672"
            - "15672:15672"
    customer-service:
        container_name: customer-service
        image: customer-service
        build: 
            context: customer-service
        ports: 
            - "4000:4000"
        networks: 
            - net
        depends_on:
            - rabbitmq
    order-service:
        container_name: order-service
        image: order-service
        build: 
            context: order-service
        ports: 
            - "3001:3001"
        networks: 
            - net
        depends_on:
            - rabbitmq
    payment-service:
        container_name: payment-service
        image: payment-service
        build: 
            context: payment-service
        ports: 
            - "5000:5000"
        networks: 
            - net
        depends_on:
            - rabbitmq
    product-service:
        container_name: product-service
        image: product-service
        build: 
            context: product-service
        ports: 
            - "5001:5001"
        networks: 
            - net
        depends_on:
            - rabbitmq
networks: 
    net:
